# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# Patched for compatibility with grpcio 1.64.x
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from agentmem._grpc import agentmem_pb2 as agentmem__pb2


class AgentMemServiceStub(object):
    """AgentMem gRPC service — remote access to all three memory types.
    Python SDK's "server" mode connects here; "embedded" mode bypasses this
    entirely and calls the Rust core in-process via PyO3.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Remember = channel.unary_unary(
                '/agentmem.AgentMemService/Remember',
                request_serializer=agentmem__pb2.RememberRequest.SerializeToString,
                response_deserializer=agentmem__pb2.RememberResponse.FromString,
                )
        self.Recall = channel.unary_unary(
                '/agentmem.AgentMemService/Recall',
                request_serializer=agentmem__pb2.RecallRequest.SerializeToString,
                response_deserializer=agentmem__pb2.RecallResponse.FromString,
                )
        self.LogEpisode = channel.unary_unary(
                '/agentmem.AgentMemService/LogEpisode',
                request_serializer=agentmem__pb2.LogEpisodeRequest.SerializeToString,
                response_deserializer=agentmem__pb2.LogEpisodeResponse.FromString,
                )
        self.GetEpisodes = channel.unary_unary(
                '/agentmem.AgentMemService/GetEpisodes',
                request_serializer=agentmem__pb2.GetEpisodesRequest.SerializeToString,
                response_deserializer=agentmem__pb2.GetEpisodesResponse.FromString,
                )
        self.SetKv = channel.unary_unary(
                '/agentmem.AgentMemService/SetKv',
                request_serializer=agentmem__pb2.SetKvRequest.SerializeToString,
                response_deserializer=agentmem__pb2.SetKvResponse.FromString,
                )
        self.GetKv = channel.unary_unary(
                '/agentmem.AgentMemService/GetKv',
                request_serializer=agentmem__pb2.GetKvRequest.SerializeToString,
                response_deserializer=agentmem__pb2.GetKvResponse.FromString,
                )


class AgentMemServiceServicer(object):
    """AgentMem gRPC service — remote access to all three memory types.
    Python SDK's "server" mode connects here; "embedded" mode bypasses this
    entirely and calls the Rust core in-process via PyO3.

    """

    def Remember(self, request, context):
        """── Semantic Memory ─────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogEpisode(self, request, context):
        """── Episodic Memory ─────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEpisodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetKv(self, request, context):
        """── Structured Memory ───────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentMemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Remember': grpc.unary_unary_rpc_method_handler(
                    servicer.Remember,
                    request_deserializer=agentmem__pb2.RememberRequest.FromString,
                    response_serializer=agentmem__pb2.RememberResponse.SerializeToString,
            ),
            'Recall': grpc.unary_unary_rpc_method_handler(
                    servicer.Recall,
                    request_deserializer=agentmem__pb2.RecallRequest.FromString,
                    response_serializer=agentmem__pb2.RecallResponse.SerializeToString,
            ),
            'LogEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.LogEpisode,
                    request_deserializer=agentmem__pb2.LogEpisodeRequest.FromString,
                    response_serializer=agentmem__pb2.LogEpisodeResponse.SerializeToString,
            ),
            'GetEpisodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEpisodes,
                    request_deserializer=agentmem__pb2.GetEpisodesRequest.FromString,
                    response_serializer=agentmem__pb2.GetEpisodesResponse.SerializeToString,
            ),
            'SetKv': grpc.unary_unary_rpc_method_handler(
                    servicer.SetKv,
                    request_deserializer=agentmem__pb2.SetKvRequest.FromString,
                    response_serializer=agentmem__pb2.SetKvResponse.SerializeToString,
            ),
            'GetKv': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKv,
                    request_deserializer=agentmem__pb2.GetKvRequest.FromString,
                    response_serializer=agentmem__pb2.GetKvResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentmem.AgentMemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentMemService(object):
    """AgentMem gRPC service — remote access to all three memory types.
    Python SDK's "server" mode connects here; "embedded" mode bypasses this
    entirely and calls the Rust core in-process via PyO3.

    """

    @staticmethod
    def Remember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmem.AgentMemService/Remember',
            agentmem__pb2.RememberRequest.SerializeToString,
            agentmem__pb2.RememberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def Recall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmem.AgentMemService/Recall',
            agentmem__pb2.RecallRequest.SerializeToString,
            agentmem__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def LogEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmem.AgentMemService/LogEpisode',
            agentmem__pb2.LogEpisodeRequest.SerializeToString,
            agentmem__pb2.LogEpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def GetEpisodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmem.AgentMemService/GetEpisodes',
            agentmem__pb2.GetEpisodesRequest.SerializeToString,
            agentmem__pb2.GetEpisodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def SetKv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmem.AgentMemService/SetKv',
            agentmem__pb2.SetKvRequest.SerializeToString,
            agentmem__pb2.SetKvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def GetKv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmem.AgentMemService/GetKv',
            agentmem__pb2.GetKvRequest.SerializeToString,
            agentmem__pb2.GetKvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)
