# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentmem.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agentmem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61gentmem.proto\x12\x08\x61gentmem\"2\n\x0fRememberRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\"\n\x10RememberResponse\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\r\"N\n\x11LogEpisodeRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x16\n\x0eresult_summary\x18\x03 \x01(\t\"?\n\x12LogEpisodeResponse\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x04\x12\x13\n\x0b\x61\x63tion_uuid\x18\x02 \x01(\t\"6\n\x12GetEpisodesRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\r\"a\n\x0c\x45pisodeEntry\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x16\n\x0eresult_summary\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x03 \x01(\x04\x12\x13\n\x0b\x61\x63tion_uuid\x18\x04 \x01(\t\"?\n\x13GetEpisodesResponse\x12(\n\x08\x65pisodes\x18\x01 \x03(\x0b\x32\x16.agentmem.EpisodeEntry\"=\n\x0cSetKvRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\"\x0f\n\rSetKvResponse\".\n\x0cGetKvRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"-\n\rGetKvResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x0c\x32\xdd\x02\n\x0f\x41gentMemService\x12\x41\n\x08Remember\x12\x19.agentmem.RememberRequest\x1a\x1a.agentmem.RememberResponse\x12G\n\nLogEpisode\x12\x1b.agentmem.LogEpisodeRequest\x1a\x1c.agentmem.LogEpisodeResponse\x12J\n\x0bGetEpisodes\x12\x1c.agentmem.GetEpisodesRequest\x1a\x1d.agentmem.GetEpisodesResponse\x12\x38\n\x05SetKv\x12\x16.agentmem.SetKvRequest\x1a\x17.agentmem.SetKvResponse\x12\x38\n\x05GetKv\x12\x16.agentmem.GetKvRequest\x1a\x17.agentmem.GetKvResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentmem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REMEMBERREQUEST']._serialized_start=28
  _globals['_REMEMBERREQUEST']._serialized_end=78
  _globals['_REMEMBERRESPONSE']._serialized_start=80
  _globals['_REMEMBERRESPONSE']._serialized_end=114
  _globals['_LOGEPISODEREQUEST']._serialized_start=116
  _globals['_LOGEPISODEREQUEST']._serialized_end=194
  _globals['_LOGEPISODERESPONSE']._serialized_start=196
  _globals['_LOGEPISODERESPONSE']._serialized_end=259
  _globals['_GETEPISODESREQUEST']._serialized_start=261
  _globals['_GETEPISODESREQUEST']._serialized_end=315
  _globals['_EPISODEENTRY']._serialized_start=317
  _globals['_EPISODEENTRY']._serialized_end=414
  _globals['_GETEPISODESRESPONSE']._serialized_start=416
  _globals['_GETEPISODESRESPONSE']._serialized_end=479
  _globals['_SETKVREQUEST']._serialized_start=481
  _globals['_SETKVREQUEST']._serialized_end=542
  _globals['_SETKVRESPONSE']._serialized_start=544
  _globals['_SETKVRESPONSE']._serialized_end=559
  _globals['_GETKVREQUEST']._serialized_start=561
  _globals['_GETKVREQUEST']._serialized_end=607
  _globals['_GETKVRESPONSE']._serialized_start=609
  _globals['_GETKVRESPONSE']._serialized_end=654
  _globals['_AGENTMEMSERVICE']._serialized_start=657
  _globals['_AGENTMEMSERVICE']._serialized_end=1006
# @@protoc_insertion_point(module_scope)
