# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agentmem_pb2 as agentmem__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agentmem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentMemServiceStub(object):
    """AgentMem gRPC service — remote access to all three memory types.
    Python SDK's "server" mode connects here; "embedded" mode bypasses this
    entirely and calls the Rust core in-process via PyO3.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Remember = channel.unary_unary(
                '/agentmem.AgentMemService/Remember',
                request_serializer=agentmem__pb2.RememberRequest.SerializeToString,
                response_deserializer=agentmem__pb2.RememberResponse.FromString,
                _registered_method=True)
        self.LogEpisode = channel.unary_unary(
                '/agentmem.AgentMemService/LogEpisode',
                request_serializer=agentmem__pb2.LogEpisodeRequest.SerializeToString,
                response_deserializer=agentmem__pb2.LogEpisodeResponse.FromString,
                _registered_method=True)
        self.GetEpisodes = channel.unary_unary(
                '/agentmem.AgentMemService/GetEpisodes',
                request_serializer=agentmem__pb2.GetEpisodesRequest.SerializeToString,
                response_deserializer=agentmem__pb2.GetEpisodesResponse.FromString,
                _registered_method=True)
        self.SetKv = channel.unary_unary(
                '/agentmem.AgentMemService/SetKv',
                request_serializer=agentmem__pb2.SetKvRequest.SerializeToString,
                response_deserializer=agentmem__pb2.SetKvResponse.FromString,
                _registered_method=True)
        self.GetKv = channel.unary_unary(
                '/agentmem.AgentMemService/GetKv',
                request_serializer=agentmem__pb2.GetKvRequest.SerializeToString,
                response_deserializer=agentmem__pb2.GetKvResponse.FromString,
                _registered_method=True)


class AgentMemServiceServicer(object):
    """AgentMem gRPC service — remote access to all three memory types.
    Python SDK's "server" mode connects here; "embedded" mode bypasses this
    entirely and calls the Rust core in-process via PyO3.

    """

    def Remember(self, request, context):
        """── Semantic Memory ─────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogEpisode(self, request, context):
        """── Episodic Memory ─────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEpisodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetKv(self, request, context):
        """── Structured Memory ───────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentMemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Remember': grpc.unary_unary_rpc_method_handler(
                    servicer.Remember,
                    request_deserializer=agentmem__pb2.RememberRequest.FromString,
                    response_serializer=agentmem__pb2.RememberResponse.SerializeToString,
            ),
            'LogEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.LogEpisode,
                    request_deserializer=agentmem__pb2.LogEpisodeRequest.FromString,
                    response_serializer=agentmem__pb2.LogEpisodeResponse.SerializeToString,
            ),
            'GetEpisodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEpisodes,
                    request_deserializer=agentmem__pb2.GetEpisodesRequest.FromString,
                    response_serializer=agentmem__pb2.GetEpisodesResponse.SerializeToString,
            ),
            'SetKv': grpc.unary_unary_rpc_method_handler(
                    servicer.SetKv,
                    request_deserializer=agentmem__pb2.SetKvRequest.FromString,
                    response_serializer=agentmem__pb2.SetKvResponse.SerializeToString,
            ),
            'GetKv': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKv,
                    request_deserializer=agentmem__pb2.GetKvRequest.FromString,
                    response_serializer=agentmem__pb2.GetKvResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentmem.AgentMemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentmem.AgentMemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentMemService(object):
    """AgentMem gRPC service — remote access to all three memory types.
    Python SDK's "server" mode connects here; "embedded" mode bypasses this
    entirely and calls the Rust core in-process via PyO3.

    """

    @staticmethod
    def Remember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmem.AgentMemService/Remember',
            agentmem__pb2.RememberRequest.SerializeToString,
            agentmem__pb2.RememberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmem.AgentMemService/LogEpisode',
            agentmem__pb2.LogEpisodeRequest.SerializeToString,
            agentmem__pb2.LogEpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEpisodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmem.AgentMemService/GetEpisodes',
            agentmem__pb2.GetEpisodesRequest.SerializeToString,
            agentmem__pb2.GetEpisodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetKv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmem.AgentMemService/SetKv',
            agentmem__pb2.SetKvRequest.SerializeToString,
            agentmem__pb2.SetKvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmem.AgentMemService/GetKv',
            agentmem__pb2.GetKvRequest.SerializeToString,
            agentmem__pb2.GetKvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
