//! gRPC server for AgentMem — remote access to all three memory types.
//!
//! # Thread Safety
//!
//! `AgentMemEmbedder` is `Send + Sync` — the underlying C++ ONNX session
//! guards `Run()` with an internal `std::mutex`.  No Rust-side locking needed.
//!
//! `AgentStorage` and `HnswIndex` are already `Send + Sync` (the former wraps
//! `Arc<DB>`, the latter uses an internal `RwLock`).

use std::sync::Arc;

use tonic::{transport::Server, Request, Response, Status};
use uuid::Uuid;

use crate::episodic::EpisodicLog;
use crate::semantic::SemanticMemory;
use crate::storage::AgentStorage;
use crate::structured::StructuredKv;
use crate::{AgentMemEmbedder, HnswIndex};

// Generated by tonic-build from proto/agentmem.proto
pub mod proto {
    tonic::include_proto!("agentmem");
}

use proto::agent_mem_service_server::{AgentMemService, AgentMemServiceServer};
use proto::{
    EpisodeEntry, GetEpisodesRequest, GetEpisodesResponse, GetKvRequest, GetKvResponse,
    LogEpisodeRequest, LogEpisodeResponse, RecallRequest, RecallResponse, RecallResult,
    RememberRequest, RememberResponse, SetKvRequest, SetKvResponse,
};

/// The core gRPC server struct.
///
/// `AgentMemEmbedder` is `Send + Sync` (C++ side has internal mutex), so
/// we wrap it in a plain `Arc` — no Rust-side `Mutex` needed.
pub struct AgentMemServer {
    embedder: Arc<AgentMemEmbedder>,
    storage: Arc<AgentStorage>,
    index: Arc<HnswIndex>,
}

impl AgentMemServer {
    pub fn new(
        embedder: AgentMemEmbedder,
        storage: AgentStorage,
        index: HnswIndex,
    ) -> Self {
        Self {
            embedder: Arc::new(embedder),
            storage: Arc::new(storage),
            index: Arc::new(index),
        }
    }
}

#[tonic::async_trait]
impl AgentMemService for AgentMemServer {
    // ── Semantic Memory ─────────────────────────────────────────────────

    async fn remember(
        &self,
        request: Request<RememberRequest>,
    ) -> Result<Response<RememberResponse>, Status> {
        let r = request.into_inner();

        let sem = SemanticMemory::new(&self.embedder, &self.storage, &self.index);

        let doc_id = sem
            .remember(&r.namespace, &r.text)
            .map_err(|e| Status::internal(format!("remember failed: {e:?}")))?;

        Ok(Response::new(RememberResponse { doc_id }))
    }

    async fn recall(
        &self,
        request: Request<RecallRequest>,
    ) -> Result<Response<RecallResponse>, Status> {
        let r = request.into_inner();
        let top_k = if r.top_k == 0 { 5 } else { r.top_k as usize };

        let sem = SemanticMemory::new(&self.embedder, &self.storage, &self.index);

        let results = sem
            .recall(&r.namespace, &r.query, top_k)
            .map_err(|e| Status::internal(format!("recall failed: {e:?}")))?;

        let results: Vec<RecallResult> = results
            .into_iter()
            .map(|(doc_id, text, score)| RecallResult {
                doc_id,
                text,
                score,
            })
            .collect();

        Ok(Response::new(RecallResponse { results }))
    }

    // ── Episodic Memory ─────────────────────────────────────────────────

    async fn log_episode(
        &self,
        request: Request<LogEpisodeRequest>,
    ) -> Result<Response<LogEpisodeResponse>, Status> {
        let r = request.into_inner();

        let log = EpisodicLog::new(&self.storage);
        let (timestamp_ns, uuid) = log
            .log_episode(&r.namespace, r.action, r.result_summary)
            .map_err(|e| Status::internal(format!("log_episode failed: {e}")))?;

        Ok(Response::new(LogEpisodeResponse {
            timestamp_ns,
            action_uuid: uuid.to_string(),
        }))
    }

    async fn get_episodes(
        &self,
        request: Request<GetEpisodesRequest>,
    ) -> Result<Response<GetEpisodesResponse>, Status> {
        let r = request.into_inner();

        let log = EpisodicLog::new(&self.storage);
        let episodes = log
            .get_episodes(&r.namespace, r.limit as usize)
            .map_err(|e| Status::internal(format!("get_episodes failed: {e}")))?;

        let entries: Vec<EpisodeEntry> = episodes
            .into_iter()
            .map(|ep| EpisodeEntry {
                action: ep.action,
                result_summary: ep.result_summary,
                timestamp_ns: ep.timestamp_ns,
                action_uuid: Uuid::from_bytes(ep.action_uuid).to_string(),
            })
            .collect();

        Ok(Response::new(GetEpisodesResponse { episodes: entries }))
    }

    // ── Structured KV ───────────────────────────────────────────────────

    async fn set_kv(
        &self,
        request: Request<SetKvRequest>,
    ) -> Result<Response<SetKvResponse>, Status> {
        let r = request.into_inner();

        let kv = StructuredKv::new(&self.storage);
        kv.set_kv(&r.namespace, &r.key, r.value)
            .map_err(|e| Status::internal(format!("set_kv failed: {e}")))?;

        Ok(Response::new(SetKvResponse {}))
    }

    async fn get_kv(
        &self,
        request: Request<GetKvRequest>,
    ) -> Result<Response<GetKvResponse>, Status> {
        let r = request.into_inner();

        let kv = StructuredKv::new(&self.storage);
        let result = kv
            .get_kv(&r.namespace, &r.key)
            .map_err(|e| Status::internal(format!("get_kv failed: {e}")))?;

        match result {
            Some(value) => Ok(Response::new(GetKvResponse { found: true, value })),
            None => Ok(Response::new(GetKvResponse {
                found: false,
                value: Vec::new(),
            })),
        }
    }
}

/// Start the gRPC server on the given address.
///
/// # Example
/// ```ignore
/// let embedder = AgentMemEmbedder::new("");
/// let storage = AgentStorage::open("/tmp/agentmem_db").unwrap();
/// let index = HnswIndex::new();
/// serve("0.0.0.0:50051", embedder, storage, index).await.unwrap();
/// ```
pub async fn serve(
    addr: &str,
    embedder: AgentMemEmbedder,
    storage: AgentStorage,
    index: HnswIndex,
) -> Result<(), Box<dyn std::error::Error>> {
    let addr = addr.parse()?;
    let server = AgentMemServer::new(embedder, storage, index);

    eprintln!("[agentmem] gRPC server listening on {addr}");

    Server::builder()
        .add_service(AgentMemServiceServer::new(server))
        .serve(addr)
        .await?;

    Ok(())
}
